###############################################################
#  Generated by:      Cadence Innovus 21.18-s099_1
#  OS:                Linux x86_64(Host ID ip-10-3-90-108)
#  Generated on:      Thu Jul 11 01:35:36 2024
#  Design:            gpio_controller
#  Command:           write_io_file ./pindeneme.io
###############################################################

(globals
    version = 3
    io_order = default
)
(iopin
)
