
// Generated by Cadence Genus(TM) Synthesis Solution 21.18-s082_1
// Generated on: Jul 11 2024 01:02:01 CEST (Jul 10 2024 23:02:01 UTC)

// Verification Directory fv/gpio_controller 

module gpio_controller(clk, rst_n, wb_dat_i, wb_dat_o, wb_adr_i,
     wb_we_i, wb_stb_i, wb_cyc_i, wb_ack_o, gpio_idr, gpio_odr);
  input clk, rst_n, wb_we_i, wb_stb_i, wb_cyc_i;
  input [31:0] wb_dat_i, wb_adr_i;
  input [15:0] gpio_idr;
  output [31:0] wb_dat_o;
  output wb_ack_o;
  output [15:0] gpio_odr;
  wire clk, rst_n, wb_we_i, wb_stb_i, wb_cyc_i;
  wire [31:0] wb_dat_i, wb_adr_i;
  wire [15:0] gpio_idr;
  wire [31:0] wb_dat_o;
  wire wb_ack_o;
  wire [15:0] gpio_odr;
  wire n_0, n_1, n_2, n_3, n_4, n_5, n_6, n_7;
  wire n_8, n_9, n_10, n_11, n_12, n_13, n_14, n_15;
  wire n_16, n_17, n_18, n_19, n_20, n_21, n_22, n_23;
  wire n_24, n_25, n_26, n_27, n_28, n_29, n_30, n_31;
  wire n_32, n_33, n_34, n_35, n_36, n_37, n_38, n_39;
  wire n_40, n_41, n_42, n_43, n_44, n_45, n_46, n_47;
  wire n_48, n_49, n_50, n_51, n_52, n_53, n_54, n_55;
  assign wb_dat_o[16] = wb_dat_o[31];
  assign wb_dat_o[17] = wb_dat_o[31];
  assign wb_dat_o[18] = wb_dat_o[31];
  assign wb_dat_o[19] = wb_dat_o[31];
  assign wb_dat_o[20] = wb_dat_o[31];
  assign wb_dat_o[21] = wb_dat_o[31];
  assign wb_dat_o[22] = wb_dat_o[31];
  assign wb_dat_o[23] = wb_dat_o[31];
  assign wb_dat_o[24] = wb_dat_o[31];
  assign wb_dat_o[25] = wb_dat_o[31];
  assign wb_dat_o[26] = wb_dat_o[31];
  assign wb_dat_o[27] = wb_dat_o[31];
  assign wb_dat_o[28] = wb_dat_o[31];
  assign wb_dat_o[29] = wb_dat_o[31];
  assign wb_dat_o[30] = wb_dat_o[31];
  SDFFRHQX1 \gpio_odr_reg[0] (.RN (rst_n), .CK (clk), .D (wb_dat_i[0]),
       .SI (gpio_odr[0]), .SE (n_55), .Q (gpio_odr[0]));
  SDFFRHQX1 \gpio_odr_reg[1] (.RN (rst_n), .CK (clk), .D (wb_dat_i[1]),
       .SI (gpio_odr[1]), .SE (n_55), .Q (gpio_odr[1]));
  SDFFRHQX1 \gpio_odr_reg[2] (.RN (rst_n), .CK (clk), .D (wb_dat_i[2]),
       .SI (gpio_odr[2]), .SE (n_55), .Q (gpio_odr[2]));
  SDFFRHQX1 \gpio_odr_reg[3] (.RN (rst_n), .CK (clk), .D (wb_dat_i[3]),
       .SI (gpio_odr[3]), .SE (n_55), .Q (gpio_odr[3]));
  SDFFRHQX1 \gpio_odr_reg[4] (.RN (rst_n), .CK (clk), .D (wb_dat_i[4]),
       .SI (gpio_odr[4]), .SE (n_55), .Q (gpio_odr[4]));
  SDFFRHQX1 \gpio_odr_reg[5] (.RN (rst_n), .CK (clk), .D (wb_dat_i[5]),
       .SI (gpio_odr[5]), .SE (n_55), .Q (gpio_odr[5]));
  SDFFRHQX1 \gpio_odr_reg[6] (.RN (rst_n), .CK (clk), .D (wb_dat_i[6]),
       .SI (gpio_odr[6]), .SE (n_55), .Q (gpio_odr[6]));
  SDFFRHQX1 \gpio_odr_reg[7] (.RN (rst_n), .CK (clk), .D (wb_dat_i[7]),
       .SI (gpio_odr[7]), .SE (n_55), .Q (gpio_odr[7]));
  SDFFRHQX1 \gpio_odr_reg[8] (.RN (rst_n), .CK (clk), .D (wb_dat_i[8]),
       .SI (gpio_odr[8]), .SE (n_55), .Q (gpio_odr[8]));
  SDFFRHQX1 \gpio_odr_reg[9] (.RN (rst_n), .CK (clk), .D (wb_dat_i[9]),
       .SI (gpio_odr[9]), .SE (n_55), .Q (gpio_odr[9]));
  SDFFRHQX1 \gpio_odr_reg[10] (.RN (rst_n), .CK (clk), .D
       (wb_dat_i[10]), .SI (gpio_odr[10]), .SE (n_55), .Q
       (gpio_odr[10]));
  SDFFRHQX1 \gpio_odr_reg[11] (.RN (rst_n), .CK (clk), .D
       (wb_dat_i[11]), .SI (gpio_odr[11]), .SE (n_55), .Q
       (gpio_odr[11]));
  SDFFRHQX1 \gpio_odr_reg[12] (.RN (rst_n), .CK (clk), .D
       (wb_dat_i[12]), .SI (gpio_odr[12]), .SE (n_55), .Q
       (gpio_odr[12]));
  SDFFRHQX1 \gpio_odr_reg[13] (.RN (rst_n), .CK (clk), .D
       (wb_dat_i[13]), .SI (gpio_odr[13]), .SE (n_55), .Q
       (gpio_odr[13]));
  SDFFRHQX1 \gpio_odr_reg[14] (.RN (rst_n), .CK (clk), .D
       (wb_dat_i[14]), .SI (gpio_odr[14]), .SE (n_55), .Q
       (gpio_odr[14]));
  SDFFRHQX1 \gpio_odr_reg[15] (.RN (rst_n), .CK (clk), .D
       (wb_dat_i[15]), .SI (gpio_odr[15]), .SE (n_55), .Q
       (gpio_odr[15]));
  DFFRHQX1 \wb_dat_o_reg[8] (.RN (rst_n), .CK (clk), .D (n_40), .Q
       (wb_dat_o[8]));
  DFFRHQX1 \wb_dat_o_reg[1] (.RN (rst_n), .CK (clk), .D (n_49), .Q
       (wb_dat_o[1]));
  DFFRHQX1 \wb_dat_o_reg[14] (.RN (rst_n), .CK (clk), .D (n_53), .Q
       (wb_dat_o[14]));
  DFFRHQX1 \wb_dat_o_reg[7] (.RN (rst_n), .CK (clk), .D (n_37), .Q
       (wb_dat_o[7]));
  DFFRHQX1 \wb_dat_o_reg[12] (.RN (rst_n), .CK (clk), .D (n_44), .Q
       (wb_dat_o[12]));
  DFFRHQX1 \wb_dat_o_reg[9] (.RN (rst_n), .CK (clk), .D (n_39), .Q
       (wb_dat_o[9]));
  DFFRHQX1 \wb_dat_o_reg[10] (.RN (rst_n), .CK (clk), .D (n_38), .Q
       (wb_dat_o[10]));
  DFFRHQX1 \wb_dat_o_reg[11] (.RN (rst_n), .CK (clk), .D (n_41), .Q
       (wb_dat_o[11]));
  DFFRHQX1 \wb_dat_o_reg[15] (.RN (rst_n), .CK (clk), .D (n_43), .Q
       (wb_dat_o[15]));
  DFFRHQX1 \wb_dat_o_reg[13] (.RN (rst_n), .CK (clk), .D (n_45), .Q
       (wb_dat_o[13]));
  DFFRHQX1 \wb_dat_o_reg[4] (.RN (rst_n), .CK (clk), .D (n_46), .Q
       (wb_dat_o[4]));
  DFFRHQX1 \wb_dat_o_reg[2] (.RN (rst_n), .CK (clk), .D (n_48), .Q
       (wb_dat_o[2]));
  DFFRHQX1 \wb_dat_o_reg[3] (.RN (rst_n), .CK (clk), .D (n_47), .Q
       (wb_dat_o[3]));
  DFFRHQX1 \wb_dat_o_reg[0] (.RN (rst_n), .CK (clk), .D (n_50), .Q
       (wb_dat_o[0]));
  DFFRHQX1 \wb_dat_o_reg[5] (.RN (rst_n), .CK (clk), .D (n_54), .Q
       (wb_dat_o[5]));
  DFFRHQX1 \wb_dat_o_reg[6] (.RN (rst_n), .CK (clk), .D (n_42), .Q
       (wb_dat_o[6]));
  DFFRHQX1 \wb_dat_o_reg[16] (.RN (rst_n), .CK (clk), .D (n_51), .Q
       (wb_dat_o[31]));
  NAND2X1 g2242__2398(.A (n_52), .B (n_23), .Y (n_54));
  NAND2X1 g2235__5107(.A (n_52), .B (n_22), .Y (n_53));
  OAI2BB1X1 g2236__6260(.A0N (n_36), .A1N (wb_dat_o[31]), .B0 (n_52),
       .Y (n_51));
  NAND2X1 g2237__4319(.A (n_52), .B (n_28), .Y (n_50));
  NAND2X1 g2238__8428(.A (n_52), .B (n_32), .Y (n_49));
  NAND2X1 g2239__5526(.A (n_52), .B (n_27), .Y (n_48));
  NAND2X1 g2240__6783(.A (n_52), .B (n_25), .Y (n_47));
  NAND2X1 g2241__3680(.A (n_52), .B (n_24), .Y (n_46));
  NAND2X1 g2234__1617(.A (n_52), .B (n_14), .Y (n_45));
  NAND2X1 g2233__2802(.A (n_52), .B (n_15), .Y (n_44));
  NAND2X1 g2244__1705(.A (n_52), .B (n_31), .Y (n_43));
  NAND2X1 g2243__5122(.A (n_52), .B (n_26), .Y (n_42));
  NAND2X1 g2228__8246(.A (n_52), .B (n_16), .Y (n_41));
  NAND2X1 g2229__7098(.A (n_52), .B (n_19), .Y (n_40));
  NAND2X1 g2230__6131(.A (n_52), .B (n_18), .Y (n_39));
  NAND2X1 g2231__1881(.A (n_52), .B (n_21), .Y (n_38));
  NAND2X1 g2232__5115(.A (n_52), .B (n_20), .Y (n_37));
  OR4X1 g2227__7482(.A (n_1), .B (n_11), .C (n_9), .D (n_35), .Y
       (n_55));
  OR2X1 g2245__4733(.A (n_36), .B (n_34), .Y (n_52));
  INVXL g2246(.A (n_34), .Y (n_35));
  NOR4X1 g2247__6161(.A (wb_adr_i[20]), .B (wb_adr_i[21]), .C (n_7), .D
       (n_33), .Y (n_34));
  NAND4XL g2248__9315(.A (n_2), .B (n_8), .C (n_4), .D (n_17), .Y
       (n_33));
  AOI222X1 g2260__9945(.A0 (gpio_idr[1]), .A1 (n_30), .B0 (n_29), .B1
       (gpio_odr[1]), .C0 (n_36), .C1 (wb_dat_o[1]), .Y (n_32));
  AOI222X1 g2258__2883(.A0 (gpio_idr[15]), .A1 (n_30), .B0 (n_29), .B1
       (gpio_odr[15]), .C0 (n_36), .C1 (wb_dat_o[15]), .Y (n_31));
  AOI222X1 g2259__2346(.A0 (gpio_idr[0]), .A1 (n_30), .B0 (n_29), .B1
       (gpio_odr[0]), .C0 (n_36), .C1 (wb_dat_o[0]), .Y (n_28));
  AOI222X1 g2261__1666(.A0 (gpio_idr[2]), .A1 (n_30), .B0 (n_29), .B1
       (gpio_odr[2]), .C0 (n_36), .C1 (wb_dat_o[2]), .Y (n_27));
  AOI222X1 g2257__7410(.A0 (gpio_idr[6]), .A1 (n_30), .B0 (n_29), .B1
       (gpio_odr[6]), .C0 (n_36), .C1 (wb_dat_o[6]), .Y (n_26));
  AOI222X1 g2262__6417(.A0 (gpio_idr[3]), .A1 (n_30), .B0 (n_29), .B1
       (gpio_odr[3]), .C0 (n_36), .C1 (wb_dat_o[3]), .Y (n_25));
  AOI222X1 g2263__5477(.A0 (gpio_idr[4]), .A1 (n_30), .B0 (n_29), .B1
       (gpio_odr[4]), .C0 (n_36), .C1 (wb_dat_o[4]), .Y (n_24));
  AOI222X1 g2264__2398(.A0 (gpio_idr[5]), .A1 (n_30), .B0 (n_29), .B1
       (gpio_odr[5]), .C0 (n_36), .C1 (wb_dat_o[5]), .Y (n_23));
  AOI222X1 g2256__5107(.A0 (gpio_idr[14]), .A1 (n_30), .B0 (n_36), .B1
       (wb_dat_o[14]), .C0 (n_29), .C1 (gpio_odr[14]), .Y (n_22));
  AOI222X1 g2249__6260(.A0 (gpio_idr[10]), .A1 (n_30), .B0 (n_36), .B1
       (wb_dat_o[10]), .C0 (n_29), .C1 (gpio_odr[10]), .Y (n_21));
  AOI222X1 g2250__4319(.A0 (gpio_idr[7]), .A1 (n_30), .B0 (n_29), .B1
       (gpio_odr[7]), .C0 (n_36), .C1 (wb_dat_o[7]), .Y (n_20));
  AOI222X1 g2251__8428(.A0 (gpio_idr[8]), .A1 (n_30), .B0 (n_36), .B1
       (wb_dat_o[8]), .C0 (n_29), .C1 (gpio_odr[8]), .Y (n_19));
  AOI222X1 g2252__5526(.A0 (gpio_idr[9]), .A1 (n_30), .B0 (n_36), .B1
       (wb_dat_o[9]), .C0 (n_29), .C1 (gpio_odr[9]), .Y (n_18));
  NOR4X1 g2253__6783(.A (wb_adr_i[6]), .B (wb_adr_i[7]), .C (n_5), .D
       (n_13), .Y (n_17));
  AOI222X1 g2254__3680(.A0 (gpio_idr[11]), .A1 (n_30), .B0 (n_36), .B1
       (wb_dat_o[11]), .C0 (n_29), .C1 (gpio_odr[11]), .Y (n_16));
  AOI222X1 g2255__1617(.A0 (gpio_idr[12]), .A1 (n_30), .B0 (n_29), .B1
       (gpio_odr[12]), .C0 (n_36), .C1 (wb_dat_o[12]), .Y (n_15));
  AOI222X1 g2265__2802(.A0 (gpio_idr[13]), .A1 (n_30), .B0 (n_29), .B1
       (gpio_odr[13]), .C0 (n_36), .C1 (wb_dat_o[13]), .Y (n_14));
  OR4X1 g2266__1705(.A (wb_adr_i[16]), .B (wb_adr_i[17]), .C (n_6), .D
       (n_10), .Y (n_13));
  AND2X1 g2267__5122(.A (n_12), .B (wb_adr_i[2]), .Y (n_29));
  AND2X1 g2268__8246(.A (n_12), .B (n_11), .Y (n_30));
  DFFRHQX1 wb_ack_o_reg(.RN (rst_n), .CK (clk), .D (n_3), .Q
       (wb_ack_o));
  INVX1 g2269(.A (n_12), .Y (n_36));
  OR4X1 g2271__7098(.A (wb_adr_i[10]), .B (wb_adr_i[11]), .C
       (wb_adr_i[13]), .D (n_0), .Y (n_10));
  NOR2X1 g2273__6131(.A (wb_we_i), .B (n_9), .Y (n_12));
  NOR3BX1 g2270__1881(.AN (wb_adr_i[31]), .B (wb_adr_i[30]), .C
       (wb_adr_i[0]), .Y (n_8));
  OR4X1 g2274__5115(.A (wb_adr_i[18]), .B (wb_adr_i[19]), .C
       (wb_adr_i[22]), .D (wb_adr_i[23]), .Y (n_7));
  OR4X1 g2275__7482(.A (wb_adr_i[1]), .B (wb_adr_i[3]), .C
       (wb_adr_i[4]), .D (wb_adr_i[5]), .Y (n_6));
  OR4X1 g2276__4733(.A (wb_adr_i[8]), .B (wb_adr_i[9]), .C
       (wb_adr_i[14]), .D (wb_adr_i[15]), .Y (n_5));
  NOR4X1 g2277__6161(.A (wb_adr_i[26]), .B (wb_adr_i[27]), .C
       (wb_adr_i[28]), .D (wb_adr_i[29]), .Y (n_4));
  INVX1 g2279(.A (n_9), .Y (n_3));
  NOR2X1 g2278__9315(.A (wb_adr_i[24]), .B (wb_adr_i[25]), .Y (n_2));
  NAND2X1 g2280__9945(.A (wb_cyc_i), .B (wb_stb_i), .Y (n_9));
  INVX1 g2282(.A (wb_we_i), .Y (n_1));
  INVX1 g2281(.A (wb_adr_i[12]), .Y (n_0));
  INVX1 g2283(.A (wb_adr_i[2]), .Y (n_11));
endmodule

