"create_clock -name clk -period 10 [get_ports "iclk"]"
"set_clock_transition -rise 0.1 [get_clocks ""clk""]"
"set_clock_transition -fall 0.1 [get_clocks ""clk""]"
"set_clock_uncertainty 0.01 [get_ports ""clk""]"
"set_input_delay -max 1.0 [get_ports ""rst_n""] -clock [get_clocks ""clk""]"
"set_input_delay -max 1.0 [get_ports ""wb_dat_i""] -clock [get_clocks ""clk""]"
"set_output_delay -max 1.0 [get_ports ""wb_dat_o""] -clock [get_clocks ""clk""]"
"set_input_delay -max 1.0 [get_ports ""wb_adr_i""] -clock [get_clocks ""clk""]"
"set_input_delay -max 1.0 [get_ports ""wb_we_i""] -clock [get_clocks ""clk""]"
"set_input_delay -max 1.0 [get_ports ""wb_stb_i""] -clock [get_clocks ""clk""]"
"set_input_delay -max 1.0 [get_ports ""wb_cyc_i""] -clock [get_clocks ""clk""]"
"set_output_delay -max 1.0 [get_ports ""wb_ack_o""] -clock [get_clocks ""clk""]"
"set_input_delay -max 1.0 [get_ports ""gpio_idr""] -clock [get_clocks ""clk""]"
"set_output_delay -max 1.0 [get_ports ""gpio_odr""] -clock [get_clocks ""clk""]"
